[External Integration] Upgrade Argo-Drupal module
tableau-mkt/argo-drupal-module pull request #2
Opened 2020-07-27 16:26 UTC by rhf104

### What? Why?
Major upgrade of Argo module. This PR is for Tableau to check up on the code quality and standards compliance while more vigorous testing happens on the spartan multidev.

2020-08-08 04:00 UTC, angrytoast commented on src/Controller/ArgoController.php
> +    $this->argoService->translate($entityType, $uuid, $translation);
- [ ] A couple of questions here
- Should this be wrapped in `try catch` since the `ArgoService::translate()` method throws multiple kinds of exceptions? Having logging around the thrown exceptions would help us debug in cases where something is failing.
- Currently the `JsonResponse` would default to HTTP 200, would it be helpful for the Spartan end to get back differing HTTP response codes?

2020-08-08 04:01 UTC, angrytoast commented on src/Controller/ArgoController.php
> +    return new Response();
Any reason this is the only regular `Response()` where as all the other controller methods use `JsonResponse()`?

2020-08-08 04:09 UTC, angrytoast commented on tests/src/Kernel/ContentEntityTranslateTest.php
> +    $this->assertEqual($translatedMetatag['key2'], $expectedTranslation);
This should also check that the original source translation's metatag values were unchanged?

2020-08-08 04:10 UTC, angrytoast commented on tests/src/Kernel/ContentEntityTranslateTest.php
> +    $this->contentEntityTranslate->translate($node, $export);
Not sure what this segment and the empty assertion below is for?

2020-08-08 04:21 UTC, angrytoast commented on tests/src/Kernel/ContentEntityTranslateTest.php
> +      $this->contentEntityTranslate->translate($updatedSrcNode, $export2);
Is there more to this test? There's a translation added here but no assertions made on it.

2020-08-08 04:35 UTC, angrytoast commented on src/ContentEntityExport.php
> +    $translationOut = ['fields' => []];
I didn't review the custom entity serialization in depth, but just checking to see that Spartan is aware of the Serialization API in Drupal core and I assume that was tried out already?

2020-08-10 19:23 UTC, angrytoast commented on argo.module
> +  $conn->insert('argo_entity_deletion')
Additionally:
- It would be good to document why Argo needs to keep track of the deleted entities, it's not very obvious what the purpose is
- It would also be good to limit it to specific entities, because many things are entities in Drupal 8, this may be unnecessarily tracking things which causes more potential issue for PDO exceptions, example from our latest dev DB:
```sql
MariaDB [pantheon]> SELECT DISTINCT(entityType) FROM argo_entity_deletion;
+---------------------------+
| entityType                |
+---------------------------+
| paragraph                 |
| path_alias                |
| node                      |
| content_moderation_state  |
| menu_position_rule        |
| menu_link_content         |
| block                     |
| slick                     |
| entity_form_display       |
| field_config              |
| field_storage_config      |
| behavior_settings         |
| redirect                  |
| context                   |
| base_field_override       |
| file                      |
| node_type                 |
| language_content_settings |
| entity_view_display       |
| menu                      |
+---------------------------+
20 rows in set (0.08 sec)
```

2020-08-31 16:16 UTC, rhf104 commented on argo.routing.yml
> +    _permission: 'Get deletion log'
Fixed

2020-08-31 16:16 UTC, rhf104 commented on argo.routing.yml
> +  methods: ['GET']
Fixed

2020-08-31 16:17 UTC, rhf104 commented on argo.info.yml
> +php: 7.2.26
Fixed

2020-08-31 16:17 UTC, rhf104 commented on src/ArgoService.php
> +    $entityFieldManager = \Drupal::service('entity_field.manager');
Fixed

2020-08-31 16:17 UTC, rhf104 commented on src/ArgoService.php
> +    $deleted = $conn->query('SELECT * FROM argo_entity_deletion')->fetchAll();
Fixed

2020-08-31 16:17 UTC, rhf104 commented on src/ArgoServiceInterface.php
> +  public function updated(string $entityType, int $lastUpdate, int $limit, int $offset);
Fixed

2020-08-31 16:18 UTC, rhf104 commented on argo.routing.yml
> +#argo.field_definitions:
Removed these unnecessary comments

2020-08-31 16:21 UTC, rhf104 commented on src/ArgoService.php
> +    $count = intval($this->updatedQuery($entityStorage, $lastUpdate, $changedFieldName,
Drupal query generator was adding an unnecessary join that was causing a 9x slowdown compared to a handwritten query. I changed the updated entity query with your suggestions and see a 1.5 second average compared to the previous 9 seconds.

2020-08-31 16:21 UTC, rhf104 commented on src/ArgoService.php
> +      $entity = $entityStorage->load($id);
Fixed

2020-08-31 16:21 UTC, rhf104 commented on src/ArgoServiceInterface.php
> +  public function entityUuid($type, $id);
Fixed

2020-08-31 16:21 UTC, rhf104 commented on argo.services.yml
> +    arguments: []
Fixed

2020-08-31 16:25 UTC, rhf104 commented on argo.module
> +  $conn->insert('argo_entity_deletion')
Replaced the insert with an upsert since there's not really a need to prevent the same entity UUID from being logged as deleted more than once. This should eliminate the possibility of that constraint violation.

Added comments describing performance need for entity deletion logging.

Reduced scope of logging to only record entities configured for translation instead of all entities.

2020-08-31 16:26 UTC, rhf104 commented on src/ContentEntityTranslate.php
> +      $special = explode('!', $path);
Added comment and improved variable naming.

2020-08-31 16:27 UTC, rhf104 commented on src/Controller/ArgoController.php
> +    $this->argoService->translate($entityType, $uuid, $translation);
Added catch blocks that log to both Drupal as well as Argo with the stacktrace in a JSON response.

2020-08-31 16:27 UTC, rhf104 commented on src/Controller/ArgoController.php
> +    return new Response();
Fixed

2020-09-08 17:58 UTC, angrytoast requested changes

2020-09-08 17:58 UTC, angrytoast commented on src/ArgoService.php
> +    SELECT base.' . $idCol . '
While the query is much faster, the concatenation used to construct it here is hard to read and potentially prone to errors.

If going with a static query, this should use `:placeholders` which removes the need for concatenation and makes the dynamic variables safer: https://www.drupal.org/docs/drupal-apis/database-api/static-queries#s-quoting-field-names-and-aliases

2020-09-13 19:38 UTC, Etroid commented on argo.module
> +      throw $e;
I think we don't want to rethrow the exception because there is nowhere to catch it.

2020-09-22 00:10 UTC, rhf104 commented on src/ArgoService.php
> +    SELECT base.' . $idCol . '
I agree this is not pleasant to read and could likely be improved using string interpolation instead of concatenation.  However I'm not sure if placeholders will work in this case. I'm using a placeholder for the 1 user-provided value (last_update), but the rest of the values are table/column names.
[Quoting field names and aliases](https://www.drupal.org/docs/drupal-apis/database-api/static-queries#s-quoting-field-names-and-aliases)
> Placeholders cannot be used for column and table names. Instead, if these are derived from unsafe input, they should be run through $database->escapeTable().

Addressing "escapeTable()": from what I can tell there is no risk of injection since all concatenated table/column names are copied from the Drupal entity definitions located in annotations (constants).

2020-09-22 00:10 UTC, rhf104 commented on argo.module
> +      throw $e;
Fixed

2020-09-22 15:22 UTC, angrytoast commented on src/ArgoService.php
> +    SELECT base.' . $idCol . '
I think using string interpolation will definitely help the readability here, it's fine to not use placeholders if they won't work.

2020-10-13 18:32 UTC, closed without merging